# Generated by Django 6.0.2 on 2026-02-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descriptions',
            field=models.TextField(blank=True, default='123', null=True),
        ),
    ]
