# Generated by Django 6.0.2 on 2026-02-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_phone', '0005_remove_category_product_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(null=True, related_name='product', to='my_phone.category'),
        ),
    ]
