# Generated by Django 6.0.2 on 2026-02-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_phone', '0006_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
    ]
