# Generated by Django 6.0.2 on 2026-02-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_phone', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product', to='my_phone.category'),
        ),
    ]
